version: "3.2"

services:
  db:
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    build: ./db
    environment:
      - "DB_USER=codechecker"
      - "DB_PASSWORD=codechecker"
      - "CONFIG_DB=codechecker_config"
      - "DEFAULT_DB=default_product"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./database_data:/var/lib/postgresql/data

  codechecker:
    container_name: codechecker
    expose:
      - "8001"
    ports:
      - "8001:8001"
    build: ./codechecker
    volumes:
      - ./src:/src
    links:
      - db
    depends_on:
      - db
    tty: true

volumes:
  database_data:
    driver: local
  src:
    driver: local
